# cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner-cluster-binding
subjects:
- kind: ServiceAccount
  name: gitlab-runner
  namespace: gitlab-runner  # The namespace where your gitlab-runner ServiceAccount is deployed
roleRef:
  kind: ClusterRole
  name: gitlab-runner-cluster-role
  apiGroup: rbac.authorization.k8s.io
